### ISSUE TITLE
Broken links nl

### ISSUE THREAD

**Issue by KwadroNaut** [mozilla-l10n/styleguides#101]
Vrijschrift-woordenboek (https://vertaling.vrijschrift.org/woordenboek) gives me a 404
Link to dictionaries from Gnome has a 404 as well: https://wiki.gnome.org/GnomeNederlandswoordenboeken.php

Couldn't find whether they're migrated or have gotten infected with bitrot.

**Comment by flodolo** [comment]
@TonnesM 
Any ideas?

**Comment by TonnesM** [comment]
The http://vertaling.vrijschrift.org/woordenboek link should still work but could use https, and the http://nl.gnome.org/woordenboeken.php link could be replaced by https://wiki.gnome.org/GnomeNederlands/Woordenlijst.

**Comment by KwadroNaut** [comment]
> The http://vertaling.vrijschrift.org/woordenboek link should still work but could use https
I had contacted yesterday some people from that organisation, it was probably broken since over a year, but they fixed it instantly.

> http://nl.gnome.org/woordenboeken.php link could be replaced by https://wiki.gnome.org/GnomeNederlands/Woordenlijst.

Different things (https://web.archive.org/web/20140927175617/http://nl.gnome.org:80/woordenboeken.php), so a rewording would be nice. I can make a pull request after the weekend.

**Comment by TonnesM** [comment]
> Different things (https://web.archive.org/web/20140927175617/http://nl.gnome.org:80/woordenboeken.php), so a rewording would be nice. I can make a pull request after the weekend.

I know, that page has gone. I think we could even do without it, as localizers should be aware of proper sources or prefer their own. Nevertheless, this could be reworded to "... of in de [lijst met online woordenlijsten](https://wiki.gnome.org/GnomeNederlands/Woordenlijst) die GNOME-NL heeft opgesteld." - let me know what you think and I can fix it prior to a PR, as well as some other things. (Another option would be to mention all dictionary links on the style guide page itself, but I don’t prefer that for maintenance reasons.)

Do note that this guide itself is just a partial copy of the one on [mozilla-nl.org](https://www.mozilla-nl.org/nl/woordenboek), both are heavily outdated, and not worth much these days IMO. Plans to revise them have been there for a while, but with low priority.

**Comment by KwadroNaut** [comment]
@TonnesM sure, that makes sense. Agree about not taking the burden of keeping such a list up-to-date. It'd be good to reference mozilla-nl.org while you're at it.

**Comment by MikkCZ** [comment]
This issue seems fixed in the current style guide published on https://mozilla-l10n.github.io/styleguides/nl/. Can you please verify @KwadroNaut?

**Comment by KwadroNaut** [comment]
Uitstekend.
