### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by flodolo** [mozilla-l10n/styleguides#106]
CC @gueroJeff @mozilla-l10n/pm-group 

The repository is currently missing a license. Should we add one? More important, can we add one that covers all the styleguides in here, or should each styleguide have its own?

**Comment by gueroJeff** [comment]
Let's do. Even Microsoft has a license agreement for their style guides. Is the MPL sufficient?

**Comment by MikkCZ** [comment]
Can we explicitly use a different license for Czech locale? We may preferr
some CC for better license interoperability with l10n.cz, but I will need
to discuss that.

**Comment by flodolo** [comment]
I don't think we can set safely a license to the entire repository, each styleguide should have their own. And in some cases we copied them from other places, where we don't have source/context.

**Comment by gueroJeff** [comment]
To my knowledge we didn't directly copy from other places, and where it
did, I thought I called it out. The ideas may have been paraphrased though.

**Comment by flodolo** [comment]
> To my knowledge we didn't directly copy from other places, and where it did, I thought I called it out.

See, for example, 
https://github.com/mozilla-l10n/styleguides/blob/master/docs/gd/
https://github.com/mozilla-l10n/styleguides/tree/master/docs/te

The Italian one was copied and pasted from a website that has it under CC. No idea about others. If they were on the WIKI, they're likely OK under MPL, but I'm far from an expert on licenses.

**Comment by gueroJeff** [comment]
I was more referring to the en-US style guide. I can't say the same about
style guides for other languages.

On Thu, Jun 21, 2018 at 11:08 AM, Francesco Lodolo <notifications@github.com

**Comment by flodolo** [comment]
> I was more referring to the en-US style guide

The question is about the entire repository, if it can have a single license, or if each license should have one. Background, I've received a question about "forking and changing this repo in other OS projects", and I'm not sure how to answer to that (license is only part of the problem).

**Comment by gueroJeff** [comment]
Was that request from LocLab?

Could we use an adaptable MLP that includes exceptions under certain
circumstances (e.g., "except for content from another licensed style guide
(source citing required), all content is licensed under MLP)?

On Thu, Jun 21, 2018 at 11:31 AM, Francesco Lodolo <notifications@github.com

**Comment by flodolo** [comment]
The request was from @drashti4, not sure which were the projects.

I don't know the answer to your question unfortunately.

**Comment by drashti4** [comment]
Yes [LocLab ](https://www.localizationlab.org) willing to adapt this styleguide but they're not sure whether they can make changes or not.

**Comment by gueroJeff** [comment]
Drashti, which style guide are they wanting to adapt, the en-US style guide
or all of them?

I would suggest they fork and make their own based on this. Style guides
should be unique to each organization's tone and style. Sometimes even
different products or content types within one organization need their own
unique style guides. Ours is a good starting place for them, but shouldn't
strictly be the one they use for all of the organizations they're
supporting.

**Comment by drashti4** [comment]
Mostly all of them. Yes, they willing to change existing Mozilla styleguide by having fork. Mozilla styleguide will not get strictly followed. But, basic structure of styleguide like JSON files will be same. So I was just wondering will it violate any copyright rules?

**Comment by gueroJeff** [comment]
There isn't an easy answer to that, as flod has pointed out. We'll consult
with Legal or whomever we need to in order to get an idea of what to do.

**Comment by MikkCZ** [comment]
@gueroJeff Any updates from legal? If not yet, is there some advise, what license to pick now to be compatible with possible future changes? I am thinking about some Creative Commons, which is widely used for written texts.

**Comment by gueroJeff** [comment]
Sorry, I don't have anything new from legal. Since the en-US style guide is
influenced by, not copy/pasted from, other company style guides, let's go
with the most relaxed CC license.
