### ISSUE TITLE
Set up Style Guide for id

### ISSUE THREAD

**Issue by peiying2** [mozilla-l10n/styleguides#146]
Requested by Indonesian community to set up the `id` version based on the content from the community team page: https://wiki.mozilla.org/L10n:Teams:id/Style_Guide

**Comment by fauzanalfi** [comment]
Thank you so much for setting up, @peiying2. Everything looks perfect. Later, we will update the guide to reflect it with current product line-up - especially region-specific products like Firefox Lite.
