### ISSUE TITLE
How can I push my update to zh_CN styleguide?

### ISSUE THREAD

**Issue by wxie2017** [mozilla-l10n/styleguides#160]
Hi,

I have made some changes/updates to zh_CN styleguide.
How can I update the repository?

best regards,
wxie

**Comment by MikkCZ** [comment]
Hi @wxie2017 .

The file with zh-CN styleguide can be found [here](https://github.com/mozilla-l10n/styleguides/blob/master/docs/zh-CN/sumo.md). You can update it here on GitHub and open a pull request. If you are not familiar with how git and GitHub works, [this article](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests) will help you.

As for the format of the file, it's written in Markdown. [Here](https://mozilla-l10n.github.io/documentation/misc/documentation_styleguide.html) are some tips how to work with it, or check [Mastering Markdown](https://guides.github.com/features/mastering-markdown/), [Basic writing and formatting syntax](https://help.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax) or [Syntax | kramdown](https://kramdown.gettalong.org/syntax.html).

**Comment by wxie2017** [comment]
Thank you.

**Comment by peiying2** [comment]
Looks like the PR was created and merged. Close the issue..
