### ISSUE TITLE
Add Cebuano (ceb) Style Guide

### ISSUE THREAD

**Issue by bobreyes** [mozilla-l10n/styleguides#199]
Contents are found in:
https://github.com/mozillaph/localization/blob/master/cebuano-style-guide.md

**Comment by Delphine** [comment]
I'm unsure if there is any action needed on our side?
I see the style guide on master branch, let me know if there's something we'd need to do. thanks!

**Comment by bobreyes** [comment]
> I'm unsure if there is any action needed on our side?
> I see the style guide on master branch, let me know if there's something we'd need to do. thanks!

Thanks, Delphine! I cannot seem to add Cebuano to https://github.com/mozilla-l10n/styleguides/tree/master/docs to make it appear on https://mozilla-l10n.github.io/styleguides/

**Comment by Delphine** [comment]
Sorry for the lag Bob. I'll get to this this week

**Comment by Delphine** [comment]
@bobreyes Done! https://github.com/mozilla-l10n/styleguides/tree/master/docs/ceb
Thanks for kicking this off Bob!
