### ISSUE TITLE
Add resources for es-ES

### ISSUE THREAD

**Issue by flodolo** [mozilla-l10n/styleguides#44]
Quick question: where does the 'es' content come from? Is it "Internation Spanish (es)" or "Spanish (es-ES)"?

I find this in es-ES, but not an es-ES folder here
http://www.proyectonave.es/glosario

**Comment by unclenachoduh** [comment]
It looks like I had this link saved as a glossary but not as a style guide. Obviously, there is a style guide at the bottom of that page. 

I can add it to the repo.

**Comment by flodolo** [comment]
OK, then we need to rename folders and links to es-ES?

**Comment by unclenachoduh** [comment]
Sorry Flod. I just understood your question. 

The link that you shared contains a short style guide for traditional Spanish (Spain) that needs to be migrated to the repo. I will do that with iso code 'es-ES'.

The folder that is labeled 'es' is generic Spanish. As far as I know, there is no ISO code for generic or international Spanish, but it is simply 'es'. It looks like that's the code on the team page too https://l10n.mozilla.org/teams/es. So the existing folder 'es' should remain as is.

**Comment by flodolo** [comment]
OK, that explains it then. Let's change this to add resources for es-ES then.

**Comment by unclenachoduh** [comment]
Resources added. Closing issue.
