### ISSUE TITLE
firefox/branding link is a 404 in German styleguide

### ISSUE THREAD

**Issue by Pike** [mozilla-l10n/styleguides#64]
We have links for Firefox branding guidelines in our styleguides, but they're a 404 now, see the search:

https://github.com/mozilla-l10n/styleguides/search?utf8=%E2%9C%93&q=firefox%2Fbranding&type=

**Comment by flodolo** [comment]
https://www.mozilla.org/en-US/styleguide/identity/firefox/branding/ redirects me to http://design.firefox.com/photon/visuals/product-identity-assets.html

**Comment by Pike** [comment]
Oh, it's just the German one pointing to /branding/0

**Comment by flodolo** [comment]
https://github.com/mozilla-l10n/styleguides/commit/c03b6a7df6c4e4b7009f88ffd9783686c2d34a7d
